SELECT T1.ID
FROM ECOLI_DATA T1
LEFT JOIN ECOLI_DATA T2
    ON T1.PARENT_ID = T2.ID
LEFT JOIN ECOLI_DATA T3
    ON T2.PARENT_ID = T3.ID
WHERE T2.ID IS NOT NULL AND T3.ID IS NOT NULL AND T3.PARENT_ID IS NULL
ORDER BY T1.ID