SELECT DISTINCT T1.USER_ID, T1.PRODUCT_ID
FROM ONLINE_SALE T1
INNER JOIN ONLINE_SALE T2
ON T1.USER_ID = T2.USER_ID AND T1.PRODUCT_ID = T2.PRODUCT_ID AND T1.ONLINE_SALE_ID != T2.ONLINE_SALE_ID
ORDER BY T1.USER_ID, T1.PRODUCT_ID DESC