SELECT FILTER_TABLE.ANIMAL_ID, FILTER_TABLE.NAME
FROM (
    SELECT 
        T1.ANIMAL_ID
    ,   T1.NAME
    ,   ROW_NUMBER() OVER(
            ORDER BY DATEDIFF(T1.DATETIME, T2.DATETIME) DESC
        ) AS ROW_NUM
    FROM ANIMAL_OUTS T1
    INNER JOIN ANIMAL_INS T2
    ON T1.ANIMAL_ID = T2.ANIMAL_ID
)   FILTER_TABLE
WHERE FILTER_TABLE.ROW_NUM IN (1, 2)
ORDER BY FILTER_TABLE.ROW_NUM