SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO T1
INNER JOIN (
    SELECT 
        REST_ID
    ,   ROW_NUMBER() OVER(
            PARTITION BY FOOD_TYPE
            ORDER BY FAVORITES DESC
        ) AS ROW_NUM
    FROM REST_INFO
) T2
ON T1.REST_ID = T2.REST_ID AND T2.ROW_NUM = 1
ORDER BY T1.FOOD_TYPE DESC