# SELECT info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS, ROUND(AVG(review.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO info INNER JOIN REST_REVIEW review ON info.REST_ID = review.REST_ID
# WHERE info.ADDRESS LIKE '%서울%'
# GROUP BY info.REST_ID
# ORDER BY SCORE DESC, info.FAVORITES DESC;

SELECT
    i.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE,
    i.FAVORITES,
    i.ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO i INNER JOIN REST_REVIEW r
    ON i.REST_ID = r.REST_ID
WHERE
    i.ADDRESS LIKE '서울%'
GROUP BY
    i.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC;