SELECT YEAR(T1.SALES_DATE) AS YEAR, MONTH(T1.SALES_DATE) AS MONTH, T2.GENDER, COUNT(DISTINCT T2.USER_ID)
FROM ONLINE_SALE T1
INNER JOIN USER_INFO T2
    ON T1.USER_ID = T2.USER_ID
WHERE T2.GENDER IS NOT NULL
GROUP BY YEAR(T1.SALES_DATE), MONTH(T1.SALES_DATE), T2.GENDER
ORDER BY YEAR(T1.SALES_DATE), MONTH(T1.SALES_DATE), T2.GENDER