SELECT T1.PRODUCT_ID, T1.PRODUCT_NAME, SUM(T1.PRICE * T2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT T1
INNER JOIN FOOD_ORDER T2
    ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE T2.PRODUCE_DATE >= '2022-05-01' AND T2.PRODUCE_DATE < '2022-06-01'
GROUP BY T1.PRODUCT_ID, T1.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, T1.PRODUCT_ID
