SELECT T1.FLAVOR
FROM FIRST_HALF T1
INNER JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) T2
    ON T1.FLAVOR = T2.FLAVOR
GROUP BY T1.FLAVOR
ORDER BY SUM(T1.TOTAL_ORDER + T2.TOTAL_ORDER) DESC
LIMIT 3