WITH RECURSIVE T1 AS (
    SELECT 0 AS VALUE
    
    UNION ALL
    
    SELECT VALUE + 1
    FROM T1
    WHERE VALUE < 23
)
SELECT T1.VALUE, COUNT(T2.ANIMAL_ID) AS COUNT
FROM T1
LEFT JOIN ANIMAL_OUTS T2
    ON T1.VALUE = HOUR(T2.DATETIME)
GROUP BY T1.VALUE
ORDER BY T1.VALUE