SELECT T1.ID, T1.EMAIL, T1.FIRST_NAME, T1.LAST_NAME
FROM DEVELOPERS T1
INNER JOIN SKILLCODES T2
    ON T1.SKILL_CODE & T2.CODE != 0 AND T2.CATEGORY = 'Front End'
GROUP BY T1.ID, T1.EMAIL, T1.FIRST_NAME, T1.LAST_NAME
ORDER BY T1.ID