WITH SUM_TABLE AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
SELECT T1.USER_ID, T1.NICKNAME, SUM_TABLE.TOTAL_SALES
FROM USED_GOODS_USER T1
INNER JOIN SUM_TABLE
ON T1.USER_ID = SUM_TABLE.WRITER_ID
ORDER BY SUM_TABLE.TOTAL_SALES