SELECT
    T1.EMP_NO
,   T1.EMP_NAME
,   CASE
        WHEN T2.AVG_SCORE >= 96 THEN 'S'
        WHEN T2.AVG_SCORE >= 90 THEN 'A'
        WHEN T2.AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE
,   CASE
        WHEN T2.AVG_SCORE >= 96 THEN T1.SAL * 0.2
        WHEN T2.AVG_SCORE >= 90 THEN T1.SAL * 0.15
        WHEN T2.AVG_SCORE >= 80 THEN T1.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES T1
    INNER JOIN (
    SELECT T1.EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_EMPLOYEES T1
    INNER JOIN HR_GRADE T2
        ON T1.EMP_NO = T2.EMP_NO
    GROUP BY T1.EMP_NO
) T2
ON T1.EMP_NO = T2.EMP_NO
ORDER BY T1.EMP_NO