SELECT T1.MEMBER_NAME, T2.REVIEW_TEXT, T2.REVIEW_DATE
FROM MEMBER_PROFILE T1
INNER JOIN REST_REVIEW T2
    ON T1.MEMBER_ID = T2.MEMBER_ID
WHERE T1.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
            SELECT COUNT(*)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(*) DESC
            LIMIT 1
    )
)
ORDER BY T2.REVIEW_DATE, T2.REVIEW_TEXT
    
