SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID IN (
    SELECT T2.ITEM_ID
    FROM ITEM_INFO T1
    INNER JOIN ITEM_TREE T2
    ON T1.ITEM_ID = T2.PARENT_ITEM_ID
    WHERE T1.RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC