SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH,
    ROW_NUMBER() OVER(
        PARTITION BY FISH_TYPE
        ORDER BY LENGTH DESC
    ) AS NUM
    FROM FISH_INFO
) T1
INNER JOIN FISH_NAME_INFO T2
ON T1.FISH_TYPE = T2.FISH_TYPE
WHERE T1.NUM = 1
ORDER BY T1.ID
