SELECT T2.SUM_SCORE, T2.EMP_NO, T1.EMP_NAME, T1.POSITION, T1.EMAIL
FROM HR_EMPLOYEES T1
INNER JOIN (
    SELECT SUM(SCORE) AS SUM_SCORE, EMP_NO, YEAR
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
) T2
ON T1.EMP_NO = T2.EMP_NO
ORDER BY T2.SUM_SCORE DESC
LIMIT 1