SELECT T1.DEPT_ID, T1.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT T1
INNER JOIN HR_EMPLOYEES T2
ON T1.DEPT_ID = T2.DEPT_ID
GROUP BY T1.DEPT_ID, T1.DEPT_NAME_EN
ORDER BY AVG_SAL DESC