SELECT
    CASE
        WHEN MAX(T2.CATEGORY = 'Front End') AND MAX(T2.NAME = 'Python') THEN 'A'
        WHEN MAX(T2.NAME = 'C#') THEN 'B'
        WHEN MAX(T2.CATEGORY = 'Front End') THEN 'C'
    END AS GRADE
,   T1.ID
,   T1.EMAIL
FROM DEVELOPERS T1
INNER JOIN SKILLCODES T2
    ON T1.SKILL_CODE & T2.CODE != 0 AND (
        T2.CATEGORY = 'Front End' OR T2.NAME = 'Python' OR T2.NAME = 'C#'
    )
GROUP BY T1.ID, T1.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, T1.ID